import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    flag: '🇬🇧',
    dir: 'ltr',
    // Navigation
    nav: {
      home: 'Home',
      library: 'My Library',
      createStory: 'Create Story',
      settings: 'Settings',
    },
    // Welcome Gallery
    welcome: {
      heroTitle: 'Create Magical Stories',
      heroSubtitle: 'for Your Little Ones',
      heroDesc: 'AI-powered personalized storybooks that spark imagination and inspire a love of reading.',
      createBtn: 'Create Your Story',
      viewLibrary: 'View My Library',
      featuredTitle: 'Featured Stories',
      howItWorksTitle: 'How It Works',
      readSample: 'Read Sample',
      readyTitle: 'Ready to Create Magic?',
      readyDesc: 'Join thousands of families creating personalized stories that spark imagination.',
      startCreating: 'Start Creating Now',
      exploreMore: 'Explore More Stories',
    },
    // Story Library
    library: {
      title: 'My Story Library',
      subtitle: 'Manage and read your personalized stories',
      searchPlaceholder: 'Search stories...',
      filterAll: 'All Stories',
      filterCompleted: 'Completed',
      filterInProgress: 'In Progress',
      sortBy: 'Sort by',
      sortNewest: 'Newest First',
      sortOldest: 'Oldest First',
      sortTitle: 'Title A-Z',
      noStories: 'No stories found',
      noStoriesDesc: 'Create your first magical story!',
      createFirst: 'Create Your First Story',
      editStory: 'Edit Story',
      saveStory: 'Save Changes',
      cancelEdit: 'Cancel',
      deleteStory: 'Delete Story',
      updateStory: 'Update Story',
      readStory: 'Read Story',
      continueReading: 'Continue Reading',
      storyTitle: 'Story Title',
      storyContent: 'Story Content',
      ageRange: 'Age Range',
      theme: 'Theme',
      pages: 'pages',
      readTime: 'read',
      progress: 'Progress',
      completed: 'Completed',
      inProgress: 'In Progress',
      confirmDelete: 'Are you sure you want to delete this story? This cannot be undone.',
      deleteConfirm: 'Yes, Delete',
      deleteCancel: 'Cancel',
      savedSuccess: 'Story saved successfully!',
      updatedSuccess: 'Story updated successfully!',
      deletedSuccess: 'Story deleted.',
      createdOn: 'Created on',
      lastRead: 'Last read',
    },
    // Story Creation Wizard
    wizard: {
      title: 'Create Your Story',
      step1: 'Age Group',
      step2: 'Theme',
      step3: 'Character',
      step4: 'Story Details',
      step5: 'Education',
      step6: 'Review',
      next: 'Next',
      back: 'Back',
      saveProgress: 'Save Progress',
      generateStory: 'Generate Story',
      selectAge: 'Select Age Group',
      selectTheme: 'Select Theme',
    },
    // Reader
    reader: {
      settings: 'Reading Settings',
      bookmarks: 'Bookmarks',
      addBookmark: 'Add Bookmark',
      exitReader: 'Exit',
      fontSize: 'Font Size',
      speed: 'Narration Speed',
      music: 'Background Music',
      progress: 'Complete',
      readMode: 'Reading Mode',
      readToMe: 'Read to Me',
      readMyself: 'Read Myself',
      followAlong: 'Follow Along',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'Something went wrong',
      retry: 'Try Again',
      close: 'Close',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      cancel: 'Cancel',
      confirm: 'Confirm',
      yes: 'Yes',
      no: 'No',
      back: 'Back',
      next: 'Next',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
    }
  },

  ta: {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    dir: 'ltr',
    nav: {
      home: 'முகப்பு',
      library: 'என் நூலகம்',
      createStory: 'கதை உருவாக்கு',
      settings: 'அமைப்புகள்',
    },
    welcome: {
      heroTitle: 'மாயமான கதைகளை உருவாக்குங்கள்',
      heroSubtitle: 'உங்கள் சிறியவர்களுக்காக',
      heroDesc: 'AI-ஆல் இயக்கப்படும் தனிப்பயனாக்கப்பட்ட கதை புத்தகங்கள் கற்பனையை தூண்டும்.',
      createBtn: 'உங்கள் கதையை உருவாக்குங்கள்',
      viewLibrary: 'என் நூலகம் காண்க',
      featuredTitle: 'சிறப்பு கதைகள்',
      howItWorksTitle: 'எப்படி செயல்படுகிறது',
      readSample: 'மாதிரி படியுங்கள்',
      readyTitle: 'மாயம் உருவாக்க தயாரா?',
      readyDesc: 'ஆயிரக்கணக்கான குடும்பங்களுடன் சேர்ந்து தனிப்பயனாக்கப்பட்ட கதைகளை உருவாக்குங்கள்.',
      startCreating: 'இப்போதே தொடங்குங்கள்',
      exploreMore: 'மேலும் கதைகள் காண்க',
    },
    library: {
      title: 'என் கதை நூலகம்',
      subtitle: 'உங்கள் தனிப்பயனாக்கப்பட்ட கதைகளை நிர்வகியுங்கள்',
      searchPlaceholder: 'கதைகளை தேடுங்கள்...',
      filterAll: 'அனைத்து கதைகள்',
      filterCompleted: 'முடிந்தவை',
      filterInProgress: 'நடந்து கொண்டிருக்கும்',
      sortBy: 'வரிசைப்படுத்து',
      sortNewest: 'புதியது முதல்',
      sortOldest: 'பழையது முதல்',
      sortTitle: 'தலைப்பு அ-ஆ',
      noStories: 'கதைகள் எதுவும் இல்லை',
      noStoriesDesc: 'உங்கள் முதல் மாயமான கதையை உருவாக்குங்கள்!',
      createFirst: 'உங்கள் முதல் கதையை உருவாக்குங்கள்',
      editStory: 'கதையை திருத்து',
      saveStory: 'மாற்றங்களை சேமி',
      cancelEdit: 'ரத்து செய்',
      deleteStory: 'கதையை நீக்கு',
      updateStory: 'கதையை புதுப்பி',
      readStory: 'கதை படி',
      continueReading: 'தொடர்ந்து படி',
      storyTitle: 'கதை தலைப்பு',
      storyContent: 'கதை உள்ளடக்கம்',
      ageRange: 'வயது வரம்பு',
      theme: 'கருப்பொருள்',
      pages: 'பக்கங்கள்',
      readTime: 'படிப்பு நேரம்',
      progress: 'முன்னேற்றம்',
      completed: 'முடிந்தது',
      inProgress: 'நடந்து கொண்டிருக்கிறது',
      confirmDelete: 'இந்த கதையை நீக்க விரும்புகிறீர்களா? இதை மீண்டும் செய்ய முடியாது.',
      deleteConfirm: 'ஆம், நீக்கு',
      deleteCancel: 'ரத்து செய்',
      savedSuccess: 'கதை வெற்றிகரமாக சேமிக்கப்பட்டது!',
      updatedSuccess: 'கதை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      deletedSuccess: 'கதை நீக்கப்பட்டது.',
      createdOn: 'உருவாக்கப்பட்ட தேதி',
      lastRead: 'கடைசியாக படித்தது',
    },
    wizard: {
      title: 'உங்கள் கதையை உருவாக்குங்கள்',
      step1: 'வயது குழு',
      step2: 'கருப்பொருள்',
      step3: 'கதாபாத்திரம்',
      step4: 'கதை விவரங்கள்',
      step5: 'கல்வி',
      step6: 'மதிப்பாய்வு',
      next: 'அடுத்து',
      back: 'பின்செல்',
      saveProgress: 'முன்னேற்றம் சேமி',
      generateStory: 'கதை உருவாக்கு',
      selectAge: 'வயது குழுவை தேர்ந்தெடுக்கவும்',
      selectTheme: 'கருப்பொருளை தேர்ந்தெடுக்கவும்',
    },
    reader: {
      settings: 'வாசிப்பு அமைப்புகள்',
      bookmarks: 'புக்மார்க்குகள்',
      addBookmark: 'புக்மார்க் சேர்',
      exitReader: 'வெளியேறு',
      fontSize: 'எழுத்து அளவு',
      speed: 'கதை வாசிப்பு வேகம்',
      music: 'பின்னணி இசை',
      progress: 'முடிந்தது',
      readMode: 'வாசிப்பு முறை',
      readToMe: 'எனக்கு படி',
      readMyself: 'நானே படிக்கிறேன்',
      followAlong: 'பின்தொடர்',
    },
    common: {
      loading: 'ஏற்றுகிறது...',
      error: 'ஏதோ தவறு நடந்தது',
      retry: 'மீண்டும் முயற்சி செய்',
      close: 'மூடு',
      save: 'சேமி',
      edit: 'திருத்து',
      delete: 'நீக்கு',
      cancel: 'ரத்து செய்',
      confirm: 'உறுதிப்படுத்து',
      yes: 'ஆம்',
      no: 'இல்லை',
      back: 'பின்செல்',
      next: 'அடுத்து',
      search: 'தேடு',
      filter: 'வடிகட்டு',
      sort: 'வரிசைப்படுத்து',
    }
  },

  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    dir: 'ltr',
    nav: {
      home: 'होम',
      library: 'मेरी लाइब्रेरी',
      createStory: 'कहानी बनाएं',
      settings: 'सेटिंग्स',
    },
    welcome: {
      heroTitle: 'जादुई कहानियां बनाएं',
      heroSubtitle: 'अपने छोटों के लिए',
      heroDesc: 'AI-संचालित व्यक्तिगत स्टोरीबुक जो कल्पना को प्रज्वलित करती हैं।',
      createBtn: 'अपनी कहानी बनाएं',
      viewLibrary: 'मेरी लाइब्रेरी देखें',
      featuredTitle: 'विशेष कहानियां',
      howItWorksTitle: 'यह कैसे काम करता है',
      readSample: 'नमूना पढ़ें',
      readyTitle: 'जादू बनाने के लिए तैयार हैं?',
      readyDesc: 'हजारों परिवारों के साथ व्यक्तिगत कहानियां बनाएं।',
      startCreating: 'अभी शुरू करें',
      exploreMore: 'और कहानियां देखें',
    },
    library: {
      title: 'मेरी कहानी लाइब्रेरी',
      subtitle: 'अपनी व्यक्तिगत कहानियां प्रबंधित करें',
      searchPlaceholder: 'कहानियां खोजें...',
      filterAll: 'सभी कहानियां',
      filterCompleted: 'पूर्ण',
      filterInProgress: 'जारी है',
      sortBy: 'क्रमबद्ध करें',
      sortNewest: 'नवीनतम पहले',
      sortOldest: 'पुराना पहले',
      sortTitle: 'शीर्षक अ-ज',
      noStories: 'कोई कहानी नहीं मिली',
      noStoriesDesc: 'अपनी पहली जादुई कहानी बनाएं!',
      createFirst: 'अपनी पहली कहानी बनाएं',
      editStory: 'कहानी संपादित करें',
      saveStory: 'बदलाव सहेजें',
      cancelEdit: 'रद्द करें',
      deleteStory: 'कहानी हटाएं',
      updateStory: 'कहानी अपडेट करें',
      readStory: 'कहानी पढ़ें',
      continueReading: 'पढ़ना जारी रखें',
      storyTitle: 'कहानी का शीर्षक',
      storyContent: 'कहानी की सामग्री',
      ageRange: 'आयु वर्ग',
      theme: 'विषय',
      pages: 'पृष्ठ',
      readTime: 'पढ़ने का समय',
      progress: 'प्रगति',
      completed: 'पूर्ण',
      inProgress: 'जारी है',
      confirmDelete: 'क्या आप इस कहानी को हटाना चाहते हैं? इसे वापस नहीं किया जा सकता।',
      deleteConfirm: 'हाँ, हटाएं',
      deleteCancel: 'रद्द करें',
      savedSuccess: 'कहानी सफलतापूर्वक सहेजी गई!',
      updatedSuccess: 'कहानी सफलतापूर्वक अपडेट की गई!',
      deletedSuccess: 'कहानी हटा दी गई।',
      createdOn: 'बनाई गई तिथि',
      lastRead: 'अंतिम पठन',
    },
    wizard: {
      title: 'अपनी कहानी बनाएं',
      step1: 'आयु वर्ग',
      step2: 'विषय',
      step3: 'पात्र',
      step4: 'कहानी विवरण',
      step5: 'शिक्षा',
      step6: 'समीक्षा',
      next: 'अगला',
      back: 'वापस',
      saveProgress: 'प्रगति सहेजें',
      generateStory: 'कहानी बनाएं',
      selectAge: 'आयु वर्ग चुनें',
      selectTheme: 'विषय चुनें',
    },
    reader: {
      settings: 'पठन सेटिंग्स',
      bookmarks: 'बुकमार्क',
      addBookmark: 'बुकमार्क जोड़ें',
      exitReader: 'बाहर निकलें',
      fontSize: 'फ़ॉन्ट आकार',
      speed: 'कथन गति',
      music: 'पृष्ठभूमि संगीत',
      progress: 'पूर्ण',
      readMode: 'पठन मोड',
      readToMe: 'मुझे पढ़ें',
      readMyself: 'मैं पढूंगा',
      followAlong: 'साथ चलें',
    },
    common: {
      loading: 'लोड हो रहा है...',
      error: 'कुछ गलत हो गया',
      retry: 'फिर से कोशिश करें',
      close: 'बंद करें',
      save: 'सहेजें',
      edit: 'संपादित करें',
      delete: 'हटाएं',
      cancel: 'रद्द करें',
      confirm: 'पुष्टि करें',
      yes: 'हाँ',
      no: 'नहीं',
      back: 'वापस',
      next: 'अगला',
      search: 'खोजें',
      filter: 'फ़िल्टर',
      sort: 'क्रमबद्ध करें',
    }
  },

  te: {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    dir: 'ltr',
    nav: {
      home: 'హోమ్',
      library: 'నా లైబ్రరీ',
      createStory: 'కథ తయారు చేయి',
      settings: 'సెట్టింగ్స్',
    },
    welcome: {
      heroTitle: 'మాయమైన కథలు తయారు చేయండి',
      heroSubtitle: 'మీ చిన్నారులకోసం',
      heroDesc: 'AI-ఆధారిత వ్యక్తిగతీకరించిన స్టోరీబుక్‌లు కల్పనను రగిలిస్తాయి.',
      createBtn: 'మీ కథను తయారు చేయండి',
      viewLibrary: 'నా లైబ్రరీ చూడండి',
      featuredTitle: 'ప్రత్యేక కథలు',
      howItWorksTitle: 'ఇది ఎలా పని చేస్తుంది',
      readSample: 'నమూనా చదవండి',
      readyTitle: 'మ్యాజిక్ తయారు చేయడానికి సిద్ధంగా ఉన్నారా?',
      readyDesc: 'వేలాది కుటుంబాలతో కలిసి వ్యక్తిగతీకరించిన కథలు తయారు చేయండి.',
      startCreating: 'ఇప్పుడే ప్రారంభించండి',
      exploreMore: 'మరిన్ని కథలు చూడండి',
    },
    library: {
      title: 'నా కథల లైబ్రరీ',
      subtitle: 'మీ వ్యక్తిగతీకరించిన కథలను నిర్వహించండి',
      searchPlaceholder: 'కథలు వెతకండి...',
      filterAll: 'అన్ని కథలు',
      filterCompleted: 'పూర్తయినవి',
      filterInProgress: 'జరుగుతున్నవి',
      sortBy: 'క్రమబద్ధీకరించు',
      sortNewest: 'కొత్తవి మొదట',
      sortOldest: 'పాతవి మొదట',
      sortTitle: 'శీర్షిక అ-హ',
      noStories: 'కథలు కనుగొనబడలేదు',
      noStoriesDesc: 'మీ మొదటి మాయమైన కథ తయారు చేయండి!',
      createFirst: 'మీ మొదటి కథ తయారు చేయండి',
      editStory: 'కథను సవరించు',
      saveStory: 'మార్పులు సేవ్ చేయి',
      cancelEdit: 'రద్దు చేయి',
      deleteStory: 'కథను తొలగించు',
      updateStory: 'కథను నవీకరించు',
      readStory: 'కథ చదవు',
      continueReading: 'చదవడం కొనసాగించు',
      storyTitle: 'కథ శీర్షిక',
      storyContent: 'కథ వివరాలు',
      ageRange: 'వయసు పరిధి',
      theme: 'థీమ్',
      pages: 'పేజీలు',
      readTime: 'చదివే సమయం',
      progress: 'పురోగతి',
      completed: 'పూర్తయింది',
      inProgress: 'జరుగుతున్నది',
      confirmDelete: 'ఈ కథను తొలగించాలని ఖచ్చితంగా ఉన్నారా? దీన్ని మళ్ళీ చేయలేరు.',
      deleteConfirm: 'అవును, తొలగించు',
      deleteCancel: 'రద్దు చేయి',
      savedSuccess: 'కథ విజయవంతంగా సేవ్ అయింది!',
      updatedSuccess: 'కథ విజయవంతంగా నవీకరించబడింది!',
      deletedSuccess: 'కథ తొలగించబడింది.',
      createdOn: 'తయారు చేసిన తేదీ',
      lastRead: 'చివరిగా చదివినది',
    },
    wizard: {
      title: 'మీ కథ తయారు చేయండి',
      step1: 'వయసు సమూహం',
      step2: 'థీమ్',
      step3: 'పాత్ర',
      step4: 'కథ వివరాలు',
      step5: 'విద్య',
      step6: 'సమీక్ష',
      next: 'తదుపరి',
      back: 'వెనుకకు',
      saveProgress: 'పురోగతి సేవ్ చేయి',
      generateStory: 'కథ తయారు చేయి',
      selectAge: 'వయసు సమూహం ఎంచుకోండి',
      selectTheme: 'థీమ్ ఎంచుకోండి',
    },
    reader: {
      settings: 'చదవడం సెట్టింగ్స్',
      bookmarks: 'బుక్‌మార్క్‌లు',
      addBookmark: 'బుక్‌మార్క్ జోడించు',
      exitReader: 'నిష్క్రమించు',
      fontSize: 'అక్షర పరిమాణం',
      speed: 'వివరణ వేగం',
      music: 'నేపథ్య సంగీతం',
      progress: 'పూర్తి',
      readMode: 'చదవడం మోడ్',
      readToMe: 'నాకు చదవు',
      readMyself: 'నేనే చదువుతాను',
      followAlong: 'అనుసరించు',
    },
    common: {
      loading: 'లోడ్ అవుతున్నది...',
      error: 'ఏదో తప్పు జరిగింది',
      retry: 'మళ్ళీ ప్రయత్నించు',
      close: 'మూయి',
      save: 'సేవ్ చేయి',
      edit: 'సవరించు',
      delete: 'తొలగించు',
      cancel: 'రద్దు చేయి',
      confirm: 'ధృవీకరించు',
      yes: 'అవును',
      no: 'కాదు',
      back: 'వెనుకకు',
      next: 'తదుపరి',
      search: 'వెతకు',
      filter: 'వడపోత',
      sort: 'క్రమబద్ధీకరించు',
    }
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('storymagic_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('storymagic_language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = translations[language]?.dir || 'ltr';
  }, [language]);

  const t = translations[language] || translations.en;

  const changeLanguage = (langCode) => {
    if (translations[langCode]) {
      setLanguage(langCode);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, translations, availableLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export default LanguageContext;
